### ISSUE TITLE
Error updating terminal log

### ISSUE THREAD

**Issue by jjpn97** [poking-agents/headless-human#37] opened 2024-11-29 16:24 UTC
![Screenshot 2024-11-11 at 16 08 44](https://github.com/user-attachments/assets/70db4122-6056-4795-9922-1add649a6358)

This occurs when running headless_human eval with --agent-settings-pack=AI_TOOLS_AVAILABLE-FULL_TERMINAL_RECORDING. Each key press in the terminal results in the log message `Error updating terminal log: FileNotFoundError(2, 'No such file or directory') in the terminal`.

This happens 30 seconds or so after starting the clock, and stops when the clock is stopped.

System: Ubuntu 20.04
Docker engine: 27.3.1

**Comment by sjawhar** [comment] 2024-12-18 17:41
Duplicate of #36

**Closed by sjawhar** 2024-12-18 17:41 UTC
Labels: bug, fix
